#!/bin/bash
echo "Running challenge setup script on vscode container"

# Adjust VSCode settings
mkdir -p /user-data/User
cat > /user-data/User/settings.json <<EOF
{
  "workbench.colorTheme": "Default Dark+"
}
EOF

# Clone the example repository
git clone https://github.com/acornies/gamify-participant.git /app

# Change directory to the cloned repository
cd /app

# Install Terraform
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

apt-get install -y wget unzip

wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint

echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list

sudo apt update

sudo apt-get install -y terraform=1.5.3-1

# Install AWS CLI
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

rm -rf awscliv2.zip aws